spring:
  profiles:
    active: mm

---

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    activate:
      on-profile: mm
  application:
    name: mm
  datasource:
    url: jdbc:postgresql://localhost:5432/pohontautan
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
  mail:
    host: in-v3.mailjet.com
    port: 587
    username: pohontautan@humanoid.net
    password: pohontautan1@

server:
  port: 9000
  maxHttpHeaderSize: 100000